apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: books-api
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: books-api
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
    argocd.argoproj.io/compare-options: IgnoreExtraneousAppLabels
spec:
  project: default
  source:
    repoURL: https://github.com/parraletz/books-api
    targetRevision: HEAD
    path: helm/books-api
    helm:
      valuesObject:
        # Image configuration
        image:
          repository: ghcr.io/parraletz/books-api
          pullPolicy: IfNotPresent
          tag: "1.0.0"
        
        # Replica configuration
        replicaCount: 2
        
        # Service configuration
        service:
          type: ClusterIP
          port: 80
          targetPort: 3000
          annotations: {}
        
        # Ingress configuration
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: books-api.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: books-api-tls
              hosts:
                - books-api.example.com
        
        # ServiceAccount and RBAC
        serviceAccount:
          create: true
          automount: true
          annotations: {}
          name: ""
        
        rbac:
          create: true
          annotations: {}
          rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "list", "watch"]
        
        # Security contexts
        podSecurityContext:
          fsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        
        # Resource limits
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        # Autoscaling (disabled by default)
        autoscaling:
          enabled: false
          minReplicas: 2
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 80
        
        # KEDA HTTP Add-on (disabled by default)
        httpScaledObject:
          enabled: false
          scaleTargetRef:
            name: ""
            service: ""
            port: 80
          replicas:
            min: 0
            max: 10
          scalingMetric:
            requestRate:
              targetValue: 100
              window: "1m"
              granularity: "1s"
          targetPendingRequests: 100
          cooldownPeriod: 300
          interceptor:
            namespace: "keda"
            service: "keda-add-ons-http-interceptor-proxy"
            port: 8080
            preserveHostHeader: true
        
        # Prometheus monitoring
        prometheus:
          enabled: true
          path: /metrics
          port: "3000"
          serviceMonitor:
            enabled: false
            namespace: ""
            labels: {}
            annotations: {}
            interval: "30s"
            scrapeTimeout: "10s"
            honorLabels: false
            metricRelabelings: []
            relabelings: []
          alerts:
            enabled: false
            namespace: ""
            labels: {}
            annotations: {}
            rules:
              highErrorRate:
                enabled: true
                threshold: 5
                for: "5m"
                severity: "critical"
                runbookUrl: ""
              highLatency:
                enabled: true
                threshold: 1
                for: "5m"
                severity: "warning"
                runbookUrl: ""
              podNotReady:
                enabled: true
                for: "5m"
                severity: "warning"
                runbookUrl: ""
              highCpuUsage:
                enabled: true
                threshold: 80
                for: "10m"
                severity: "warning"
                runbookUrl: ""
              highMemoryUsage:
                enabled: true
                threshold: 80
                for: "10m"
                severity: "warning"
                runbookUrl: ""
              podRestarting:
                enabled: true
                threshold: 3
                for: "5m"
                severity: "warning"
                runbookUrl: ""
              noPodsRunning:
                enabled: true
                for: "1m"
                severity: "critical"
                runbookUrl: ""
            customRules: []
        
        # OpenTelemetry (disabled by default)
        opentelemetry:
          enabled: false
          endpoint: "http://otel-collector:4318"
          serviceName: "books-api"
          debug: false
        
        # Grafana dashboards (disabled by default)
        grafana:
          dashboards:
            enabled: false
            labels:
              grafana_dashboard: "1"
            annotations: {}
        
        # Environment variables
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3000"
        
        # Environment variables from ConfigMaps/Secrets
        envFrom: []
        
        # Node selector, tolerations, affinity
        nodeSelector: {}
        tolerations: []
        affinity: {}
        
        # Volumes and volume mounts
        volumes: []
        volumeMounts: []
        
        # Pod annotations and labels
        podAnnotations: {}
        podLabels: {}
        
        # Image pull secrets
        imagePullSecrets: []
        
        # Name overrides
        nameOverride: ""
        fullnameOverride: ""
  
  destination:
    server: https://kubernetes.default.svc
    namespace: books-api
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas